base_path:
log_path:
data:
  event2member_path: ./data/event2member.txt
  event_id_path: ./data/event_id.txt
  member_id_path: ./data/member_id.txt
  event2group_path: ./data/event2group.txt
  group2member_path: ./data/group2member.txt
  train_ratio: 0.7
  valid_ratio: 0.1
  time_sequence_length: 10

train:
  epochs: 100
  gpuid: 1
  save: false
  save_path: ./log

test:
  epoch: 100

model:
  model_type: GCN
  in_feats: 2
  h_feats: 32